### PR TITLE
(cleanup) Updated preamble.js

### PR DESCRIPTION
**Pull request by zzmp**
##### This commit makes the following changes:
- Note EXPORTED_FUNCTIONS when saying that mangled functions fail
- Reference malloc as _malloc, as this is how it is called form Module
- Fix formatting in setValue/getValue
- Change array buffer to ArrayBuffer
- Remove outdated note to link TYPED ARRAYS MODE2 DOCUMENTATION

---

I'm not sure if this is the right place to contribute to these docs. If it is not, could you point me to the right place? I couldn't find the `site/` mentioned by the `Readme`.

Also, I'd love to help out more in this project. Is it appropriate to be looking at the docs? Is there somewhere I can be of more use, having just been introduced to the project?

### CODE REVIEW

**Comment by kripken** [comment]
Thanks for this!

I think though that the proper procedure is a pull request into the `emscripten` repo, to change the source files under `site/`. The files in this repo are basically the output of those files. @hamishwillee would know for sure if the files here are not an exception.

**Comment by zzmp** [comment]
@kripken @hamishwillee I can't find a site folder in the `emscripten` repo (kripken/emscripken). Has it been pushed? Am I missing it?

**Comment by kripken** [comment]
Oh, sorry, it is just on the `incoming` branch currently. It is very new.

**Comment by hamishwillee** [comment]
Thanks zzmp.

The normal procedure is that you "should" be encouraged to fix these yourself. However I've got some outstanding commits on that file so I'll have a look at this and fix them myself (assuming that is OK)

And FYI, build instructions are here: http://kripken.github.io/emscripten-site/docs/site/about.html

**Comment by hamishwillee** [comment]
PS

> I'm not sure if this is the right place to contribute to these docs. If it is not, could you point me to the right place? I couldn't find the site/ mentioned by the Readme.

Yes, the incoming branch is the right place to get the source, and the [about](http://kripken.github.io/emscripten-site/docs/site/about.html#page-management-markup) file says how. 

> Also, I'd love to help out more in this project. Is it appropriate to be looking at the docs? Is there somewhere I can be of more use, having just been introduced to the project?

Any help you can give would be much appreciated.

For the docs, the best place you can help me with that is in reviewing pages that are [ready for review](http://kripken.github.io/emscripten-site/docs/site/about.html#page-management-markup). The rest of the documents are still being looked at and I haven't finalised locations or content yet - it you have advice then we can discuss.

As for "general" contribution, check out the [contributing](http://kripken.github.io/emscripten-site/docs/contributing/contributing.html) page. Again, bug fixing is a very good place to get started.

**Comment by hamishwillee** [comment]
OK, I've fixed some of these in my branch (which I hope to commit tonight). You can see if you're happy in my snapshot here: https://dl.dropboxusercontent.com/u/3067678/emscripten-site/docs/api_reference/preamble.js.html

> Reference malloc as _malloc, as this is how it is called form Module

Thanks, changed everywhere.

> Note EXPORTED_FUNCTIONS when saying that mangled functions fail

Generally the mangling is only mentioned in context of C++ functions, and EXPORTED_FUNCTIONS doesn't help with that (only with minification, and inlining etc)

I've re-written parts of this to make it clearer in the current version - including better explanation of when you use EXPORTED... . So I think the snapshot should address your issues

> Fix formatting in setValue/getValue

Already fixed in my latest version

> Change array buffer to ArrayBuffer

I think you are referring to "type array buffer is". I've updated this to "typed array buffer is" which is correct.

> Remove outdated note to link TYPED ARRAYS MODE2 DOCUMENTATION
> Done

FYI, I have comments throughout the docs that I hope to remove at the end. They should be invisible in the rendered copy. 

Thanks for your help!

**Comment by zzmp** [comment]
I think changing "type" to "typed" is appropriate, but I was referring to the JavaScript `ArrayBuffer`, as that is what the heaps are implemented as.

As this sentence just refers to the underlying implementation, it could be more clear as

> a typed JavaScript `ArrayBuffer` is used to represent memory,

Other than that, everything looks great. I'll look through the pages needing review and contribute what I can.

**Comment by hamishwillee** [comment]
Thanks for clarification. I've done (but not pushed or published yet):

> a typed array buffer (`ArrayBuffer`) is used
> 
> Other than that, everything looks great. I'll look through the pages needing review and contribute what I can.

Fantastic. Please start on articles that either have no page title markup (meaning I think that they are complete) and "ready-for-review".

**Comment by kripken** [comment]
I think we can close this, as the work has been done elsewhere.

**Comment by hamishwillee** [comment]
Yes, this can be closed.

**Pull request closed without merging**
