### PR TITLE
Update from emscripten incoming branch

### PR DESCRIPTION
**Pull request by sbc100**
This is the result of running `make html` in emscripten/site and copying
the result but also first remove the _source/_static and docs tree.

I think previous updates perhaps had not removed old file which is
why there are quite a few deletes present here.

### CODE REVIEW

**Comment by sbc100** [comment]
I'd like to verify that all of these change are actually valid and that building from `incoming` should give the exact same results both for both of us.    I'm going to rebuild again not to make sure its at least idempotent on my machine.

**Comment by kripken** [comment]
I think the .txt changes are not needed - only the HTML files are viewed on the website.

However, I vaguely remember that some of the source files are needed for some reason, but not sure why.

**Comment by sbc100** [comment]
if the .txt changes are not needed we should not have them checked in here I guess?

**Comment by sbc100** [comment]
At it looks like the .txt files are used for the "View page source" links at the bottom of each page.

https://emscripten.org/ make page links to: 
https://emscripten.org/_sources/index.rst.txt

But it should be:
https://emscripten.org/_sources/index.txt

I guess the best place to link to would really be the github source for the rst file?  But I think this is a biggger change.  For now, given that the .txt files exist, should we update them rather than having stale ones?

**Review by kripken — APPROVED** [review]
Hmm, those "view page source" links are new to me - never noticed them before :smile: but they aren't what I was thinking of. I think there was something else.

Anyhow, this seems good to me. The one odd thing is the many minor changes to existing pages, which I guess are that you have a different sphinx version. But I guess you viewed the output locally and it all looks fine?

**Comment by sbc100** [comment]
Yup. looks find to me.

Can you run `make install` locally once this lands and see if you have any diff?  Any upload them so we can see the differences?

**Comment by kripken** [comment]
I do have quite a large diff after this landed, 5.6 MB.

It starts with
```diff
diff --git a/_static/basic.css b/_static/basic.css
index 0b79414..0807176 100644
--- a/_static/basic.css
+++ b/_static/basic.css
@@ -4,7 +4,7 @@
  *
  * Sphinx stylesheet -- basic theme.
  *
- * :copyright: Copyright 2007-2016 by the Sphinx team, see AUTHORS.
+ * :copyright: Copyright 2007-2019 by the Sphinx team, see AUTHORS.
  * :license: BSD, see LICENSE for details.
  *
  */
@@ -81,10 +81,26 @@ div.sphinxsidebar input {
     font-size: 1em;
 }
 
+div.sphinxsidebar #searchbox form.search {
+    overflow: hidden;
+}
+
 div.sphinxsidebar #searchbox input[type="text"] {
-    width: 170px;
+    float: left;
+    width: 80%;
+    padding: 0.25em;
+    box-sizing: border-box;
+}
+
+div.sphinxsidebar #searchbox input[type="submit"] {
+    float: left;
+    width: 20%;
+    border-left: none;
+    padding: 0.25em;
+    box-sizing: border-box;
 }
 
+
 img {
     border: 0;
     max-width: 100%;
```

Note the copyright years. Maybe our versions are very different? I have
```bash
$ sphinx-build --version
sphinx-build 1.8.5
```

**Pull request merged**
